<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="192"
    height="192"
    fill="#750cdf"
    viewBox="0 0 256 256"
  >
    <rect
      x="24"
      y="56"
      width="208"
      height="144"
      rx="8"
      fill="none"
      stroke="#750cdf"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="16"
    />
    <line
      x1="168"
      y1="168"
      x2="200"
      y2="168"
      fill="none"
      stroke="#750cdf"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="16"
    />
    <line
      x1="120"
      y1="168"
      x2="136"
      y2="168"
      fill="none"
      stroke="#750cdf"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="16"
    />
    <line
      x1="24"
      y1="96.9"
      x2="232"
      y2="96.9"
      fill="none"
      stroke="#750cdf"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="16"
    />
  </svg>
</template>

<script lang="ts" setup></script>
